[package]
edition = "2021"
name = "pspp"
version = "0.1.0"

[features]
default = ["crossbeam"]
flume = ["dep:flume"]
crossbeam = ["crossbeam-channel"]
ff = ["ff_buffer"]
kanal = ["dep:kanal"]

[profile.release]
debug = false

[dependencies]
core_affinity = "0.8.0"
crossbeam-channel = { version = "0.5.8", optional = true }
crossbeam-deque = "0.8.2"
dyn-clone = "1.0.10"
log = "0.4.17"
num_cpus = "1.0"
ff_buffer = { git = "https://github.com/valebes/ff_buffer.git", optional = true }
kanal = { git = "https://github.com/fereidani/kanal.git", optional = true }
flume = { version = "0.10.14", optional = true }

[dev-dependencies]
criterion = {version = "0.4", features = ["html_reports"]}
crossbeam-channel = { version = "0.5.8"}
dashmap = "5.4.0"
env_logger = "0.10.0"
rand = "*"
raster = {git = "https://github.com/valebes/raster.git"}
rayon = "1.6.1"
rust-spp = {git = "https://github.com/GMAP/rust-ssp.git"}
num_cpus = "1.15.0"
serial_test = "*"
scopeguard = "1.1.0"

[[bench]]
harness = false
name = "image_processing"
