[package]
name = "pspp"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10.0"
dyn-clone = "1.0.10"
rand = "*"
core_affinity = "0.8.0"
raster = "0.2.0"
